extern crate proc_macro;

use quote::quote;
use syn::{ItemFn, parse_macro_input};

#[proc_macro_attribute]
pub fn log_handler(
    attr: proc_macro::TokenStream,
    item: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    // let input_fn = parse_macro_input!(item as ItemFn);
    // let generate = quote! {
    //         //调用属性宏
    //         println!("log proc_macro_attribute is call !");
    //     #input_fn
    // };
    // generate.into();
    let function_name = attr.to_string();
    let mut item_string = item.to_string();
    item_string.push_str(&format!("fn {}() {{", function_name));
    item_string
        .push_str("println!(\"This is a custom function generated by attribute macro!\"); }");
    item_string.parse().unwrap()
}
